import { opendir } from "node:fs/promises";
import { relative, resolve } from "node:path";

export interface CodebaseSummary {
  codebaseSummary: string;
  packageStructure: string;
  architecture: string;
}

export interface CodebaseResult extends CodebaseSummary {
  provider: "codebase-memory-mcp" | "fallback-file-scan";
  degraded: boolean;
  reason?: string;
}

export interface McpTransport {
  isAvailable(): Promise<boolean>;
  index(root: string): Promise<void>;
  summarize(root: string): Promise<CodebaseSummary>;
}

const EXCLUDED_DIRECTORIES = new Set([
  ".git",
  ".sdd",
  "node_modules",
  "target",
  "build",
  "dist",
  "coverage",
  "logs",
]);

export class CodebaseAdapter {
  constructor(private readonly transport?: McpTransport) {}

  async initialize(root: string): Promise<CodebaseResult> {
    if (this.transport !== undefined && (await this.transport.isAvailable())) {
      await this.transport.index(root);
      return {
        provider: "codebase-memory-mcp",
        degraded: false,
        ...(await this.transport.summarize(root)),
      };
    }
    const files = await scanFiles(root);
    const directories = [
      ...new Set(files.map((file) => file.split("/").slice(0, -1).join("/"))),
    ]
      .filter(Boolean)
      .sort();
    return {
      provider: "fallback-file-scan",
      degraded: true,
      reason: "codebase-memory-mcp unavailable",
      codebaseSummary: [
        "# Codebase Summary",
        "",
        ...files.map((file) => `- ${file}`),
      ].join("\n"),
      packageStructure: [
        "# Package Structure",
        "",
        ...directories.map((dir) => `- ${dir}`),
      ].join("\n"),
      architecture: [
        "# Architecture",
        "",
        "Generated by bounded fallback file scan; symbol and call relationships are unavailable.",
        "",
        `Files discovered: ${files.length}`,
      ].join("\n"),
    };
  }
}

async function scanFiles(root: string, limit = 2_000): Promise<string[]> {
  const absoluteRoot = resolve(root);
  const result: string[] = [];
  const queue = [absoluteRoot];
  while (queue.length > 0 && result.length < limit) {
    const directory = queue.shift();
    if (directory === undefined) break;
    const handle = await opendir(directory);
    for await (const entry of handle) {
      if (entry.name.startsWith(".") && entry.name !== ".github") continue;
      const absolute = resolve(directory, entry.name);
      if (entry.isDirectory()) {
        if (!EXCLUDED_DIRECTORIES.has(entry.name)) queue.push(absolute);
      } else if (entry.isFile()) {
        if (isSecretFile(entry.name)) continue;
        result.push(relative(absoluteRoot, absolute).split("\\").join("/"));
        if (result.length >= limit) break;
      }
    }
  }
  return result.sort();
}

function isSecretFile(name: string): boolean {
  const lower = name.toLowerCase();
  return (
    lower === "id_rsa" ||
    lower === "id_ed25519" ||
    lower === "kubeconfig" ||
    lower === "application-prod.yml" ||
    lower === "application-prod.yaml" ||
    lower === "application-prod.properties" ||
    [".pem", ".key", ".p12", ".jks"].some((extension) =>
      lower.endsWith(extension),
    )
  );
}
